version: '3'

services:
  openvidu-server-kms:
    image: "openvidu/openvidu-server-kms:2.11.0"
    environment:
      - openvidu.webhook=true
      - openvidu.webhook.endpoint=http://host.docker.internal:8080/api/v1/ov/webhooks
      - openvidu.webhook.events=["webrtcConnectionCreated","webrtcConnectionDestroyed"]
      - openvidu.secret=MY_SECRET
      - openvidu.publicurl=https://localhost:4443
    ports:
      - "4443:4443"

  fiware-integration-manager:
    image: "node:8"
    working_dir: /home/node/app
    #    environment:
    #      - NODE_ENV=production
    volumes:
      - ../fiware-integration-manager:/home/node/app
    command: "npm start"
    ports:
      - "3000:3000"
