version: '3.6'

services:
  kms:
    build:
      context: ./
      dockerfile: Dockerfile.kms.platedetector
    image: kms-platedetector:latest
    environment:
      - GST_DEBUG="3,Kurento*:4,kms*:4,sdp*:4,webrtc*:4,*rtpendpoint:4,rtp*handler:4,rtpsynchronizer:4,agnosticbin:4"
    networks:
      kms-net:
        aliases:
          - kms

  openvidu-server:
    image: "openvidu/openvidu-server:nightly-20191003"
    environment:
      - openvidu.webhook=true
      - openvidu.webhook.endpoint=http://host.docker.internal:8080/api/v1/ov/webhooks
      - openvidu.webhook.events=["webrtcConnectionCreated","webrtcConnectionDestroyed","filterEventDispatched"]
      - openvidu.secret=MY_SECRET
      - openvidu.publicurl=https://localhost:4443
      - kms.uris=["ws://kms:8888/kurento"]
    ports:
      - "4443:4443"
    depends_on:
      - kms
    networks:
      kms-net:

  fiware-integration-manager:
    image: "node:8"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ../fiware-integration-manager:/home/node/app
    command: "npm start"
    ports:
      - "3000:3000"

  orion-mongo:
    image: "mongo:3.6"
    ports:
      - "27017:27017"
    networks:
      orion-net:
        aliases:
          - mongo

  orion:
    image: "fiware/orion"
    ports:
      - "1026:1026"
    networks:
      orion-net:
    depends_on:
      - orion-mongo
    command: -dbhost mongo

  fiware-integration:
    build:
      context: ./
      dockerfile: Dockerfile.java.app
    environment:
      - publicurl=http://localhost:8080
      - openvidu.publicurl=https://host.docker.internal:4443
      - openvidu.filterurl=http://host.docker.internal:9090
      - openvidu.secret=MY_SECRET
      - orion.publicurl=http://host.docker.internal:1026
      - develop=true
    image: java-app:latest
    ports:
      - "8080:8080"
    volumes:
      - ./fiware-integration.jar:/app.jar
    depends_on:
      - orion
      - openvidu-server

  openvidu-filters-client:
    image: java-app:latest
    restart: always
    environment:
      - OPENVIDU_URL=https://host.docker.internal:4443/
      - OPENVIDU_SECRET=MY_SECRET
    ports:
      - "9090:9090"
    volumes:
      - ./openvidu-filters-client.jar:/app.jar
    depends_on:
      - orion
      - openvidu-server

networks:
  orion-net:
  kms-net:
