version: '3.6'

services:
  kms:
    build:
      context: ./
      dockerfile: Dockerfile.kms.platedetector
    image: kms-platedetector:latest
    environment:
      - GST_DEBUG="3,Kurento*:4,kms*:4,sdp*:4,webrtc*:4,*rtpendpoint:4,rtp*handler:4,rtpsynchronizer:4,agnosticbin:4"
   
  openvidu-server:
    image: "openvidu/openvidu-server:nightly-20191003"
    environment:
      - openvidu.webhook=true
      - openvidu.webhook.endpoint=http://fiware-integration:8080/api/v1/ov/webhooks
      - openvidu.webhook.events=["webrtcConnectionCreated","webrtcConnectionDestroyed","filterEventDispatched"]
      - openvidu.secret=MY_SECRET
      - openvidu.publicurl=docker
      - kms.uris=["ws://kms:8888/kurento"]
    expose:
      - 4443
    depends_on:
      - kms
   
  fiware-integration-manager:
    build:
      context: ../
      dockerfile: docker/Dockerfile.fiware.integration.manager.app
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    expose:
      - 3000
    depends_on:
      - orion

  orion-mongo:
    image: "mongo:3.6"
    expose:
      - 27017
   
  orion:
    image: "fiware/orion"
    expose:
      - 1026
    depends_on:
      - orion-mongo
    command: -dbhost orion-mongo

  fiware-integration:
    build:
      context: ./
      dockerfile: Dockerfile.java.app
    image: java-app:latest
    environment:
      - publicurl=http://fiware-integration:8080
      - openvidu.publicurl=https://openvidu-server:4443
      - openvidu.filterurl=http://openvidu-filters-client:9090
      - openvidu.secret=MY_SECRET
      - orion.publicurl=http://orion:1026
    expose:
      - 8080
    depends_on:
      - orion
      - openvidu-server

  openvidu-filters-client:
    build:
      context: ./
      dockerfile: Dockerfile.openvidu.filters.client
    image: openvidu-filters-client:latest
    restart: always
    environment:
      - OPENVIDU_URL=https://openvidu-server:4443/
      - OPENVIDU_SECRET=MY_SECRET
    expose:
      - 9090
    depends_on:
      - orion
      - openvidu-server
